apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policy
  namespace: argocd
spec:
  project: gatekeeper-policy
  source:
    repoURL: https://github.com/tf2-team/tf2-corp-chart.git
    targetRevision: main
    path: gitops/gatekeeper
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
