apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - policies/cluster-image-policy.yaml

helmCharts:
  - name: policy-controller
    repo: https://sigstore.github.io/helm-charts
    version: 0.9.0
    releaseName: policy-controller
    namespace: cosign-system
    valuesInline:
      webhook:
        serviceAccount:
          create: true
          name: policy-controller
        failurePolicy: Ignore
