# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  accounting:
    imageOverride:
      digest: "sha256:1b708e9b31af0ccbf7dbc7de124ecc7c3c310cae6586efc510a21db05cae6995"
