# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  fraud-detection:
    imageOverride:
      digest: "sha256:1c78d03436a02d5a23c1536f56b55572aac52d52a625a7f772a2a385b7888812"
