# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  ad:
    imageOverride:
      digest: "sha256:1114006c40147d79676d4fe3a323f49b7041172fd05cf3b305c5ea1e6a738dbf"
