# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  ad:
    imageOverride:
      digest: "sha256:223f6409630c09666312d322c5dbfe083b421b31e75eee72831a3128b56d2b7d"
