# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  frontend:
    imageOverride:
      digest: "sha256:745273578a6c9b47928317680171ab6681b1c11c0a2f035c15eef13b27c76d45"
