# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  llm:
    imageOverride:
      digest: "sha256:4bd60c1255b905d49f094ce72942ffc5b1049a101a7faf6435b347ec9a3dbbc7"
