# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  shipping:
    imageOverride:
      digest: "sha256:a7aaa45cc56ff9949b11edd4d148fae2d3de64e94d278c0149070b3fe24bec27"
