# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @datpn02 - 2026-07-22 - Update verified production ECR digest for load-generator master and worker.
components:
  load-generator:
    imageOverride:
      digest: "sha256:80cdb7981dd8cf4b92554b7803582ab4507921ffeaf337f5dce323224a5bd51e"
  load-generator-worker:
    imageOverride:
      digest: "sha256:80cdb7981dd8cf4b92554b7803582ab4507921ffeaf337f5dce323224a5bd51e"
