# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  ad:
    imageOverride:
      digest: "sha256:d67411cae9f916bd41d782565b510f6127718ccf36c46be557ad81ec4bcacbb8"
