# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  llm:
    imageOverride:
      digest: "sha256:464588467080740592da4ea62bbe654f9601a634f410273e73bf8e9585d9fe13"
