# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  checkout:
    imageOverride:
      digest: "sha256:f0d4f8ed4db281456ea0ec3402cae258df147796b0b54d9d65e665ffcc808481"
