# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  product-catalog:
    imageOverride:
      digest: "sha256:30b8c80e8a89419d0b05d8d91484b9be48f77ea0b14dd3d0af658350e83bc24f"
