# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  opensearch:
    imageOverride:
      digest: "sha256:2e3441353f15ebe090bb536e1f72fc1970fbbad4b133a1624526037a621336aa"
