# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  image-provider:
    imageOverride:
      digest: "sha256:40b740ec3978770e8d01eb7e034611ead6d42f0b25c668c81ff391b7c121cd42"
