# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  checkout:
    imageOverride:
      digest: "sha256:3fa6bee886801e2822be206a8a8a57a19525ab87a0069a768eb6a2265199e6cf"
