# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @datpn02 - 2026-07-22 - Update verified production ECR digest for load-generator master and worker.
components:
  load-generator:
    imageOverride:
      digest: "sha256:b5dc8ec7d29c4649064799d82597ffdb9609790cd0fb818d7a94913899666b55"
  load-generator-worker:
    imageOverride:
      digest: "sha256:b5dc8ec7d29c4649064799d82597ffdb9609790cd0fb818d7a94913899666b55"
