# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @datpn02 - 2026-07-22 - Update verified production ECR digest for load-generator master and worker.
components:
  load-generator:
    imageOverride:
      digest: "sha256:5e533cd5d2b0f1c64d006ce9505af976b6ec2a384b271d8faf4b9dafe52cf0cb"
  load-generator-worker:
    imageOverride:
      digest: "sha256:5e533cd5d2b0f1c64d006ce9505af976b6ec2a384b271d8faf4b9dafe52cf0cb"
