# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  product-catalog:
    imageOverride:
      digest: "sha256:9ebd24d0fad6c062a5b70d83e275b72120e7120d027b506e2f6b4ba7dd4cae40"
