# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  opensearch:
    imageOverride:
      digest: "sha256:d5cb17de16d65279caa32a950c8ac28d8654f4df2077bb9389b8f7d57ac8c84c"
