# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  checkout:
    imageOverride:
      digest: "sha256:35bedad761ed6486d292c622dde66c837c6793c0e6efbcbc9a6e56bc149413e7"
