# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  shipping:
    imageOverride:
      digest: "sha256:bf26299221aa7b5dfdb053f8dbdae187b2f00296f005a33440ca20f407973839"
