apiVersion: v1
kind: ServiceAccount
metadata:
  name: policy-controller
  namespace: cosign-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::493499579600:role/techx-prod-tf2-policy-controller
