apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: policy.sigstore.dev
webhooks:
  - name: validation.policy.sigstore.dev
    clientConfig:
      service:
        name: policy-controller
        namespace: cosign-system
        path: /validate
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: policy.sigstore.dev/include
          operator: In
          values: ["true"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
