apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: runtime-hardening-pod-enforce.techx.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  policyName: runtime-hardening-pod.techx.io
  validationActions: [Deny]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: runtime-hardening-pod-template-enforce.techx.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  policyName: runtime-hardening-pod-template.techx.io
  validationActions: [Deny]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: runtime-hardening-cronjob-enforce.techx.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  policyName: runtime-hardening-cronjob.techx.io
  validationActions: [Deny]
