apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: service-account-patch.yaml
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: MutatingWebhookConfiguration
      name: policy.sigstore.dev
    patch: |-
      - op: replace
        path: /webhooks/0/failurePolicy
        value: Fail
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: policy.sigstore.dev
    patch: |-
      - op: replace
        path: /webhooks/0/failurePolicy
        value: Fail
